"""The WS server. **Core is the hub**, so Core listens, and Shell and Stage connect to it.

Startup sequence → docs/architecture/core.md §7
Boundaries → docs/contracts/security-boundaries.md B2 (Core ↔ Stage) / B3 (Core → Shell)

## Authentication

The token is generated by Shell when it launches the sidecar, and handed to Core via
**an environment variable** (never on the command line → docs/interfaces/shell.md).
Core binds only to 127.0.0.1.

**A different token is used per role.** Sharing one would let a compromised Stage
claim `role: "shell"` and hijack `os.*` commands. Shell generates both and only hands
the Stage-specific one to the Stage.

## What this layer does not guarantee

Any process that knows the token can connect. **Preventing connections from other
processes on the same machine holds only as long as the token hasn't leaked.**
Nothing beyond that (e.g. verifying process signatures) is done here.
"""

from __future__ import annotations

import asyncio
import secrets
from collections.abc import Awaitable, Callable, Mapping
from typing import Any

from websockets.asyncio.server import Server, ServerConnection, serve
from websockets.exceptions import ConnectionClosed

from lumi import logging as lumi_logging
from lumi.transport.protocol import (
    HELLO_TIMEOUT_S,
    PING_INTERVAL_S,
    PING_TIMEOUT_S,
    Command,
    Notify,
    ProtocolError,
    Request,
    Result,
    Role,
    Welcome,
    method_matches_role,
    new_id,
    parse_client_message,
    parse_hello,
)

log = lumi_logging.get_logger(__name__)

#: The close code returned on authentication failure (1000-2999 is reserved, so the 4000s are used).
CLOSE_UNAUTHORIZED = 4401
CLOSE_PROTOCOL_ERROR = 4400

#: The default timeout for a command. **Never waits silently forever** for a response.
DEFAULT_COMMAND_TIMEOUT_S = 10.0

#: How long an inbound handler may take before the request is answered `timeout` anyway.
#: `_serve_request` promises to always answer, and a handler that blocks forever is the one
#: way that promise breaks — the client cannot tell it apart from a hung Core.
INBOUND_REQUEST_TIMEOUT_S = 10.0


#: A handler for a Stage → Core request. Returns the payload to answer with, or raises
#: `RequestRefused` to answer with an error (ADR-028).
InboundHandler = Callable[[dict[str, Any]], Awaitable[dict[str, Any]]]


class RequestRefused(Exception):
    """The handler refused. **The reason travels back to the client**, never just "failed"."""

    def __init__(self, reason: str) -> None:
        super().__init__(reason)
        self.reason = reason


class NotConnectedError(RuntimeError):
    """The peer isn't connected. **Raised as an exception so this never silently degrades.**"""


class CommandFailedError(RuntimeError):
    """The peer refused it, or execution failed."""


class _Connection:
    """One authenticated connection. At most one per role."""

    def __init__(self, role: Role, ws: ServerConnection) -> None:
        self.role = role
        self.ws = ws
        self._pending: dict[str, asyncio.Future[Result]] = {}

    def register(self, command_id: str) -> asyncio.Future[Result]:
        future: asyncio.Future[Result] = asyncio.get_running_loop().create_future()
        self._pending[command_id] = future
        return future

    def resolve(self, result: Result) -> bool:
        future = self._pending.pop(result.corr_id, None)
        if future is None:
            return False
        if not future.done():
            future.set_result(result)
        return True

    def abandon_all(self, reason: str) -> None:
        """The connection dropped. **Fails any pending commands with an error** (never leaves them
        hanging).
        """
        for command_id, future in self._pending.items():
            if not future.done():
                future.set_exception(NotConnectedError(f"{command_id}: {reason}"))
        self._pending.clear()


ConnectHook = Callable[[Role], Awaitable[None]]


class WsServer:
    """Core's WS server."""

    def __init__(
        self,
        tokens: Mapping[Role, str],
        *,
        host: str = "127.0.0.1",
        port: int = 0,
        on_connect: ConnectHook | None = None,
        on_disconnect: ConnectHook | None = None,
    ) -> None:
        # Tokens are separated per role. **Sharing one would let a compromised Stage
        # connect as shell and hijack os.*** (docs/contracts/security-boundaries.md B2/B3).
        missing = [role.value for role in Role if not tokens.get(role)]
        if missing:
            raise ValueError(f"token が空: {missing}。認証なしで listen しない（fail-closed）")
        self._tokens = dict(tokens)
        self._host = host
        self._requested_port = port
        self._on_connect = on_connect
        self._on_disconnect = on_disconnect
        self._connections: dict[Role, _Connection] = {}
        # : **The allowlist for the Stage → Core direction** (ADR-028). A method not
        # : registered here is unreachable — the allowlist is the registry itself, so
        # : adding a route is always a deliberate act rather than a missing check.
        self._inbound: dict[str, InboundHandler] = {}
        self._server: Server | None = None
        #: In-flight inbound requests. **Kept referenced or the GC collects them**
        self._requests: set[asyncio.Task[None]] = set()
        self._port: int | None = None

    @property
    def port(self) -> int:
        if self._port is None:
            raise RuntimeError("まだ listen していない")
        return self._port

    def is_connected(self, role: Role) -> bool:
        return role in self._connections

    async def start(self) -> int:
        """Starts listening and returns the actual port number."""
        self._server = await serve(
            self._handle,
            self._host,
            self._requested_port,
            ping_interval=PING_INTERVAL_S,
            ping_timeout=PING_TIMEOUT_S,
        )
        sockets = list(self._server.sockets)
        if not sockets:
            raise RuntimeError("listen に失敗した")
        self._port = int(sockets[0].getsockname()[1])
        return self._port

    async def stop(self) -> None:
        if self._server is not None:
            self._server.close()
            await self._server.wait_closed()
            self._server = None

    # ASYNC109: Leaving `asyncio.timeout` to the caller means **it waits forever**
    # whenever it's forgotten. To "never silently degrade," the API carries a
    # timeout with a default.
    def on_request(self, method: str, handler: InboundHandler) -> None:
        """Registers a method the client may initiate. **The allowlist is this registry**
        (ADR-028) — anything unregistered is answered `unknown_method`.

        Registering is deliberately explicit: **a route that nobody wrote down does not
        exist**, which is the fail-closed shape the boundary needs.
        """
        if method in self._inbound:
            raise ValueError(f"{method} は既に登録されている")
        self._inbound[method] = handler

    async def _serve_request(self, connection: _Connection, request: Request) -> None:
        """Answers one inbound request. **Always answers** — a client left waiting forever
        is indistinguishable from a hung Core.
        """
        handler = self._inbound.get(request.method)
        if handler is None or not method_matches_role(request.method, connection.role):
            # **fail-closed.** An unregistered method, or one outside this role's
            # namespace, is refused without ever reaching any handler
            log.warning(
                "transport.request.refused",
                role=connection.role.value,
                method=request.method,
                registered=handler is not None,
            )
            await self._answer(connection, request, ok=False, error="unknown_method")
            return

        try:
            async with asyncio.timeout(INBOUND_REQUEST_TIMEOUT_S):
                payload = await handler(request.payload)
        except RequestRefused as refused:
            log.info("transport.request.refused", method=request.method, reason=refused.reason)
            await self._answer(connection, request, ok=False, error=refused.reason)
        except TimeoutError:
            # **The client gets an answer even when the handler never came back.** Waiting
            # forever on a request is indistinguishable from Core having died
            log.warning("transport.request.timeout", method=request.method)
            await self._answer(connection, request, ok=False, error="timeout")
        except Exception:
            # **Never leaks the exception text to the client.** It is logged in full here
            log.exception("transport.request.failed", method=request.method)
            await self._answer(connection, request, ok=False, error="internal_error")
        else:
            await self._answer(connection, request, ok=True, payload=payload)

    async def _answer(
        self,
        connection: _Connection,
        request: Request,
        *,
        ok: bool,
        payload: dict[str, Any] | None = None,
        error: str | None = None,
    ) -> None:
        frame = Result(corr_id=request.id, ok=ok, payload=payload or {}, error=error)
        try:
            await connection.ws.send(frame.encode())
        except ConnectionClosed:
            # The client went away mid-request. **Not worth failing over**
            log.debug("transport.answer.closed", role=connection.role.value, method=request.method)
        except Exception:
            # Anything else — an unencodable payload above all — is a Core-side bug that
            # **leaves the client waiting.** Suppressing it silently is how it stays invisible
            log.exception(
                "transport.answer.failed", role=connection.role.value, method=request.method
            )

    async def invoke(
        self,
        role: Role,
        method: str,
        payload: dict[str, Any] | None = None,
        *,
        timeout: float = DEFAULT_COMMAND_TIMEOUT_S,  # noqa: ASYNC109
    ) -> Result:
        """Sends a command and waits for the result.

        **A mismatch between namespace and role is rejected before sending.**
        So no path ever exists for `os.*` to reach the Stage (B2).
        """
        if not method_matches_role(method, role):
            raise ValueError(f"{role.value} に {method} は送れない（namespace 違反）")

        connection = self._connections.get(role)
        if connection is None:
            raise NotConnectedError(f"{role.value} が接続していない")

        command = Command(id=new_id(), method=method, payload=payload or {})
        future = connection.register(command.id)
        try:
            await connection.ws.send(command.to_json())
            return await asyncio.wait_for(future, timeout)
        except TimeoutError:
            log.warning("transport.command.timeout", role=role.value, method=method)
            raise
        finally:
            connection.resolve(Result(corr_id=command.id, ok=False, payload={}, error="cleanup"))

    async def notify(self, role: Role, method: str, payload: dict[str, Any] | None = None) -> None:
        """Sends without waiting for a result. **Never raises even if the peer isn't connected.**

        A notification is "nice if it arrives" — not arriving isn't a failure.
        Unlike `invoke`, stalling here would let a UI update block Core's own progress.
        """
        if not method_matches_role(method, role):
            raise ValueError(f"{role.value} に {method} は送れない（namespace 違反）")

        connection = self._connections.get(role)
        if connection is None:
            log.debug("transport.notify.dropped", role=role.value, method=method)
            return
        try:
            await connection.ws.send(Notify(method=method, payload=payload or {}).to_json())
        except ConnectionClosed:
            log.debug("transport.notify.closed", role=role.value, method=method)

    async def _handle(self, ws: ServerConnection) -> None:
        role = await self._authenticate(ws)
        if role is None:
            return

        connection = _Connection(role, ws)
        previous = self._connections.get(role)
        if previous is not None:
            # A reconnect. The old one is discarded (never leaves a ghost connection on Core's
            # side).
            log.info("transport.reconnect", role=role.value)
            previous.abandon_all("再接続で置き換えられた")
            await previous.ws.close(code=1000, reason="replaced by a new connection")

        self._connections[role] = connection
        log.info("transport.connected", role=role.value)
        if self._on_connect is not None:
            await self._on_connect(role)

        try:
            await self._receive_loop(connection)
        finally:
            if self._connections.get(role) is connection:
                del self._connections[role]
                connection.abandon_all("接続が閉じた")
                log.info("transport.disconnected", role=role.value)
                if self._on_disconnect is not None:
                    await self._on_disconnect(role)

    async def _authenticate(self, ws: ServerConnection) -> Role | None:
        """Waits for hello and verifies the token. **Closes on failure.**"""
        try:
            raw = await asyncio.wait_for(ws.recv(), HELLO_TIMEOUT_S)
        except TimeoutError:
            log.warning("transport.hello.timeout")
            await ws.close(code=CLOSE_UNAUTHORIZED, reason="hello timeout")
            return None
        except ConnectionClosed:
            return None

        if isinstance(raw, bytes):
            log.warning("transport.hello.binary")
            await ws.close(code=CLOSE_PROTOCOL_ERROR, reason="hello must be text")
            return None

        try:
            hello = parse_hello(raw)
        except ProtocolError as exc:
            log.warning("transport.hello.invalid", reason=str(exc))
            await ws.close(code=CLOSE_PROTOCOL_ERROR, reason="invalid hello")
            return None

        # The comparison is done in a way that avoids timing attacks. **Only checked against the
        # token for the claimed role.**
        if not secrets.compare_digest(hello.token, self._tokens[hello.role]):
            log.warning("transport.auth.rejected", role=hello.role.value)
            await ws.close(code=CLOSE_UNAUTHORIZED, reason="invalid token")
            return None

        await ws.send(Welcome().to_json())
        return hello.role

    async def _receive_loop(self, connection: _Connection) -> None:
        async for raw in connection.ws:
            if isinstance(raw, bytes):
                log.warning("transport.message.binary", role=connection.role.value)
                await connection.ws.close(code=CLOSE_PROTOCOL_ERROR, reason="text only")
                return
            try:
                message = parse_client_message(raw)
            except ProtocolError as exc:
                # The client broke the contract. **Closed instead of being swallowed.**
                log.warning(
                    "transport.message.invalid", role=connection.role.value, reason=str(exc)
                )
                await connection.ws.close(code=CLOSE_PROTOCOL_ERROR, reason="protocol error")
                return

            if isinstance(message, Request):
                # **Handled in its own task.** A slow handler must not stop this
                # connection from reading the next frame (a `result` Core is waiting on
                # could be queued behind it)
                task = asyncio.create_task(
                    self._serve_request(connection, message), name="ws-request"
                )
                self._requests.add(task)
                task.add_done_callback(self._requests.discard)
                continue

            if not connection.resolve(message):
                log.warning(
                    "transport.result.unknown_corr_id",
                    role=connection.role.value,
                    corr_id=message.corr_id,
                )


#: The environment variable carrying the token for each role. **Never put on the command line.**
TOKEN_ENV_BY_ROLE: dict[Role, str] = {
    Role.SHELL: "LUMI_WS_TOKEN_SHELL",
    Role.STAGE: "LUMI_WS_TOKEN_STAGE",
}


def tokens_from_env(env: Mapping[str, str]) -> tuple[dict[Role, str], bool]:
    """Retrieves the per-role token from environment variables. Generates one if missing.

    The second return value is "was one generated." **Generation only happens in
    dev**; the production path launched from Shell always supplies these via
    environment variables.
    """
    tokens: dict[Role, str] = {}
    generated = False
    for role, name in TOKEN_ENV_BY_ROLE.items():
        value = env.get(name, "")
        if not value:
            value = secrets.token_urlsafe(32)
            generated = True
        tokens[role] = value
    return tokens, generated
