"""The WS server. **Core is the hub**, so Core listens, and Shell and Stage connect to it.

Startup sequence → docs/architecture/core.md §7
Boundaries → docs/contracts/security-boundaries.md B2 (Core ↔ Stage) / B3 (Core → Shell)

This module is the socket: listening, the handshake, reading frames, and the two ways Core
speaks outward (`invoke` and `notify`). **Who is connected** lives in
`transport/connections.py` and **what an inbound request is allowed to reach** lives in
`transport/router.py` — the second of those is a security boundary, and it is easier to
read as a rule when it is not interleaved with socket bookkeeping.

## Authentication

The token is generated by Shell when it launches the sidecar, and handed to Core via
**an environment variable** (never on the command line → docs/interfaces/shell.md).
Core binds only to 127.0.0.1.

**A different token is used per role.** Sharing one would let a compromised Stage
claim `role: "shell"` and hijack `os.*` commands. Shell generates both and only hands
the Stage-specific one to the Stage.

## What this layer does not guarantee

Any process that knows the token can connect. **Preventing connections from other
processes on the same machine holds only as long as the token hasn't leaked.**
Nothing beyond that (e.g. verifying process signatures) is done here.
"""

from __future__ import annotations

import asyncio
import secrets
from collections.abc import Awaitable, Callable, Mapping
from typing import Any

from websockets.asyncio.server import Server, ServerConnection, serve
from websockets.exceptions import ConnectionClosed

from lumi import logging as lumi_logging
from lumi.tasks import spawn
from lumi.transport.connections import (
    CLOSE_PROTOCOL_ERROR,
    CLOSE_UNAUTHORIZED,
    Connection,
    ConnectionRegistry,
    NotConnectedError,
)
from lumi.transport.protocol import (
    HELLO_TIMEOUT_S,
    PING_INTERVAL_S,
    PING_TIMEOUT_S,
    Command,
    Notify,
    ProtocolError,
    Request,
    Result,
    Role,
    Welcome,
    method_matches_role,
    new_id,
    parse_client_message,
    parse_hello,
)
from lumi.transport.router import InboundHandler, Router

log = lumi_logging.get_logger(__name__)

#: The default timeout for a command. **Never waits silently forever** for a response.
DEFAULT_COMMAND_TIMEOUT_S = 10.0

ConnectHook = Callable[[Role], Awaitable[None]]


class WsServer:
    """Core's WS server."""

    def __init__(
        self,
        tokens: Mapping[Role, str],
        *,
        host: str = "127.0.0.1",
        port: int = 0,
        on_connect: ConnectHook | None = None,
        on_disconnect: ConnectHook | None = None,
    ) -> None:
        # Tokens are separated per role. **Sharing one would let a compromised Stage
        # connect as shell and hijack os.*** (docs/contracts/security-boundaries.md B2/B3).
        missing = [role.value for role in Role if not tokens.get(role)]
        if missing:
            raise ValueError(
                f"Empty token for {missing}; will not listen without authentication (fail-closed)"
            )
        self._tokens = dict(tokens)
        self._host = host
        self._requested_port = port
        self._on_connect = on_connect
        self._on_disconnect = on_disconnect
        self._connections = ConnectionRegistry()
        self._router = Router()
        self._server: Server | None = None
        #: In-flight inbound requests. **Kept referenced or the GC collects them**
        self._requests: set[asyncio.Task[None]] = set()
        self._shutting_down = False
        self._port: int | None = None

    @property
    def port(self) -> int:
        if self._port is None:
            raise RuntimeError("Server is not listening yet")
        return self._port

    def is_connected(self, role: Role) -> bool:
        return self._connections.is_connected(role)

    def connection_count(self, role: Role) -> int:
        """How many clients hold this role. **Only `panel` ever exceeds 1.**"""
        return self._connections.count(role)

    async def start(self) -> int:
        """Starts listening and returns the actual port number."""
        self._shutting_down = False
        self._server = await serve(
            self._handle,
            self._host,
            self._requested_port,
            ping_interval=PING_INTERVAL_S,
            ping_timeout=PING_TIMEOUT_S,
        )
        sockets = list(self._server.sockets)
        if not sockets:
            raise RuntimeError("Failed to listen")
        self._port = int(sockets[0].getsockname()[1])
        return self._port

    async def stop(self) -> None:
        self._shutting_down = True
        server = self._server
        if server is not None:
            # Stop accepting connections immediately, but don't wait for closure until all
            # inbound request handlers have been canceled and awaited below.
            server.close()

        # A request runs independently of the receive loop. **Closing the listener does not
        # cancel a handler that is already awaiting**, and allowing it to continue would let
        # Core state change after shutdown has begun.
        current = asyncio.current_task()
        pending = tuple(task for task in self._requests if task is not current)
        for task in pending:
            task.cancel()
        if pending:
            await asyncio.gather(*pending, return_exceptions=True)

        if server is not None:
            await server.wait_closed()
            self._server = None

    def on_request(self, method: str, handler: InboundHandler) -> None:
        """Registers a method the client may initiate. **The allowlist is that registry**
        (ADR-028) — anything unregistered is answered `unknown_method`
        (`transport/router.py`).
        """
        self._router.register(method, handler)

    # ASYNC109: Leaving `asyncio.timeout` to the caller means **it waits forever**
    # whenever it's forgotten. To "never silently degrade," the API carries a
    # timeout with a default.
    async def invoke(
        self,
        role: Role,
        method: str,
        payload: dict[str, Any] | None = None,
        *,
        timeout: float = DEFAULT_COMMAND_TIMEOUT_S,  # noqa: ASYNC109
    ) -> Result:
        """Sends a command and waits for the result.

        **A mismatch between namespace and role is rejected before sending.**
        So no path ever exists for `os.*` to reach the Stage (B2).
        """
        if not method_matches_role(method, role):
            raise ValueError(f"Cannot send {method} to {role.value} (namespace violation)")
        # **A command waits for an answer, so it needs one addressee** (ADR-042). Panels
        # are notified, never commanded, and this is the check that keeps that true.
        connection = self._connections.sole(role)
        if connection is None:
            raise NotConnectedError(f"{role.value} is not connected")

        command = Command(id=new_id(), method=method, payload=payload or {})
        future = connection.register(command.id)
        try:
            await connection.ws.send(command.to_json())
            return await asyncio.wait_for(future, timeout)
        except TimeoutError:
            log.warning("transport.command.timeout", role=role.value, method=method)
            raise
        finally:
            connection.resolve(Result(corr_id=command.id, ok=False, payload={}, error="cleanup"))

    async def notify(self, role: Role, method: str, payload: dict[str, Any] | None = None) -> None:
        """Sends without waiting for a result. **Never raises even if the peer isn't connected.**

        A notification is "nice if it arrives" — not arriving isn't a failure.
        Unlike `invoke`, stalling here would let a UI update block Core's own progress.

        **Goes to every connection holding the role.** For `panel` that is however many
        windows the user has open, including none at all (ADR-042).
        """
        if not method_matches_role(method, role):
            raise ValueError(f"Cannot send {method} to {role.value} (namespace violation)")

        peers = self._connections.peers(role)
        if not peers:
            log.debug("transport.notify.dropped", role=role.value, method=method)
            return
        frame = Notify(method=method, payload=payload or {}).to_json()
        for connection in peers:
            try:
                await connection.ws.send(frame)
            except ConnectionClosed:
                # One window closing is not the other windows' problem.
                log.debug("transport.notify.closed", role=role.value, method=method)

    async def _handle(self, ws: ServerConnection) -> None:
        role = await self._authenticate(ws)
        if role is None:
            return

        connection = Connection(role, ws)
        peers = await self._connections.admit(connection)
        log.info("transport.connected", role=role.value, peers=peers)
        if self._on_connect is not None:
            await self._on_connect(role)

        try:
            await self._receive_loop(connection)
        finally:
            remaining = self._connections.release(connection)
            if remaining is not None:
                log.info("transport.disconnected", role=role.value, peers=remaining)
                # **Fires for every closing connection, panel included.** A hook that only
                # ran for the last one would never fire for a role that usually still has
                # another window open.
                if self._on_disconnect is not None:
                    await self._on_disconnect(role)

    async def _authenticate(self, ws: ServerConnection) -> Role | None:
        """Waits for hello and verifies the token. **Closes on failure.**"""
        try:
            raw = await asyncio.wait_for(ws.recv(), HELLO_TIMEOUT_S)
        except TimeoutError:
            log.warning("transport.hello.timeout")
            await ws.close(code=CLOSE_UNAUTHORIZED, reason="hello timeout")
            return None
        except ConnectionClosed:
            return None

        if isinstance(raw, bytes):
            log.warning("transport.hello.binary")
            await ws.close(code=CLOSE_PROTOCOL_ERROR, reason="hello must be text")
            return None

        try:
            hello = parse_hello(raw)
        except ProtocolError as exc:
            log.warning("transport.hello.invalid", reason=str(exc))
            await ws.close(code=CLOSE_PROTOCOL_ERROR, reason="invalid hello")
            return None

        # The comparison is done in a way that avoids timing attacks. **Only checked against the
        # token for the claimed role.**
        if not secrets.compare_digest(hello.token, self._tokens[hello.role]):
            log.warning("transport.auth.rejected", role=hello.role.value)
            await ws.close(code=CLOSE_UNAUTHORIZED, reason="invalid token")
            return None

        await ws.send(Welcome().to_json())
        return hello.role

    async def _receive_loop(self, connection: Connection) -> None:
        async for raw in connection.ws:
            if self._shutting_down:
                return
            if isinstance(raw, bytes):
                log.warning("transport.message.binary", role=connection.role.value)
                await connection.ws.close(code=CLOSE_PROTOCOL_ERROR, reason="text only")
                return
            try:
                message = parse_client_message(raw)
            except ProtocolError as exc:
                # The client broke the contract. **Closed instead of being swallowed.**
                log.warning(
                    "transport.message.invalid", role=connection.role.value, reason=str(exc)
                )
                await connection.ws.close(code=CLOSE_PROTOCOL_ERROR, reason="protocol error")
                return

            if isinstance(message, Request):
                # **Handled in its own task.** A slow handler must not stop this
                # connection from reading the next frame (a `result` Core is waiting on
                # could be queued behind it)
                spawn(
                    self._router.serve(connection, message),
                    name="ws-request",
                    event="transport.request_crashed",
                    keep=self._requests,
                )
                continue

            if not connection.resolve(message):
                log.warning(
                    "transport.result.unknown_corr_id",
                    role=connection.role.value,
                    corr_id=message.corr_id,
                )


#: The environment variable carrying the token for each role. **Never put on the command line.**
TOKEN_ENV_BY_ROLE: dict[Role, str] = {
    Role.SHELL: "LUMI_WS_TOKEN_SHELL",
    Role.STAGE: "LUMI_WS_TOKEN_STAGE",
    Role.PANEL: "LUMI_WS_TOKEN_PANEL",
}


def tokens_from_env(env: Mapping[str, str]) -> tuple[dict[Role, str], bool]:
    """Retrieves the per-role token from environment variables. Generates one if missing.

    The second return value is "was one generated." **Generation only happens in
    dev**; the production path launched from Shell always supplies these via
    environment variables.
    """
    tokens: dict[Role, str] = {}
    generated = False
    for role, name in TOKEN_ENV_BY_ROLE.items():
        value = env.get(name, "")
        if not value:
            value = secrets.token_urlsafe(32)
            generated = True
        tokens[role] = value
    return tokens, generated
